# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  versionTag: ''

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site" /p:RuntimeIdentifier="win7-x64" /p:TargetLatestRuntimePatch="true"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: NuGetCommand@2
#   displayName: 'NuGet package'
#   inputs:
#     command: pack
#     packagesToPack: '$(Build.ArtifactStagingDirectory)/LuhnValidator/*.csproj'
#     versioningScheme: byPrereleaseNumber
#     majorVersion: '1'
#     minorVersion: '0'
#     patchVersion: '1' 

- script: |
    echo 'starting'
    echo 'init'
    set $myVar=`git tag`
    set $myVar2="git tag"
    echo $myVar
    echo $myVar2
    echo "##vso[task.setvariable variable=versionTag]$myVar"
  displayName: 'Nuget push '

- script: echo $(versionTag)
  displayName: 'NN'

# - script: "dotnet pack -p:Version=1.0.1"
#   displayName: 'NuGet package'

# - task: NuGetCommand@2
#   displayName: 'NuGet push'
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/LuhnValidator/bin/Debug/LuhnValidator.1.0.1.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'MyNugetPackage'

# - script: "dotnet nuget push LuhnValidator\\bin\\Debug\\LuhnValidator.1.0.1.nupkg -k $(NUGET_KEY) -s https://api.nuget.org/v3/index.json"
#   displayName: 'NuGet push'

