# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  versionTag: 'git tag'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site" /p:RuntimeIdentifier="win7-x64" /p:TargetLatestRuntimePatch="true"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: NuGetCommand@2
#   displayName: 'NuGet package'
#   inputs:
#     command: pack
#     packagesToPack: '$(Build.ArtifactStagingDirectory)/LuhnValidator/*.csproj'
#     versioningScheme: byPrereleaseNumber
#     majorVersion: '1'
#     minorVersion: '0'
#     patchVersion: '1' 
# - script: $(versionTag)
#   displayName: 'NN1'

- bash: |
    versionTag=`git tag` 
    echo "##vso[task.setvariable variable=VERSION_TAG]$versionTag"
    "dotnet pack -p:Version=$(VERSION_TAG)"
    "dotnet nuget push LuhnValidator\\bin\\Debug\\LuhnValidator.$(VERSION_TAG).nupkg -k $(NUGET_KEY) -s https://api.nuget.org/v3/index.json"
  displayName: 'Nuget push '

# - script: $(VERSION_TAG)
#   displayName: 'NN'

# - bash: |
#     "dotnet pack -p:Version=$(versionTag)"
#     "dotnet nuget push LuhnValidator\\bin\\Debug\\LuhnValidator.$(versionTag).nupkg -k $(NUGET_KEY) -s https://api.nuget.org/v3/index.json"
#   displayName: 'NuGet package'

# - task: NuGetCommand@2
#   displayName: 'NuGet push'
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/LuhnValidator/bin/Debug/LuhnValidator.1.0.1.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'MyNugetPackage'

# - script: "dotnet nuget push LuhnValidator\\bin\\Debug\\LuhnValidator.1.0.1.nupkg -k $(NUGET_KEY) -s https://api.nuget.org/v3/index.json"
#   displayName: 'NuGet push'

